// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizApi.Models;

#nullable disable

namespace QuizApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220505210429_IniciandoBase")]
    partial class IniciandoBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuizApi.Models.Questao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("descricaoQuestao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idMateria")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Questoes");
                });

            modelBuilder.Entity("QuizApi.Models.Quiz", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("idAluno")
                        .HasColumnType("int");

                    b.Property<int>("materiaQuiz")
                        .HasColumnType("int");

                    b.Property<int>("quantidadeQuestoes")
                        .HasColumnType("int");

                    b.Property<int>("questoesCorretas")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("tempoQuiz")
                        .HasColumnType("time");

                    b.HasKey("id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("QuizApi.Models.Resposta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("descricaoResposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idQuestao")
                        .HasColumnType("int");

                    b.Property<int>("idtCorreta")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Respostas");
                });
#pragma warning restore 612, 618
        }
    }
}
